name: deepdefocus_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - pandas
  - mrcfile
  - scipy
  - scikit-image
  - tensorflow
  - scikit-learn
  - pip
  - pip:
      - sqlite3  # Included via pip as it's usually built into Python
