name: deepdefocus_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - pandas
  - mrcfile
  - scipy
  - scikit-image
  - tensorflow
  - scikit-learn
  - sqlite3
  - pip
